### ISSUE TITLE
Core Pieces

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/formcore#19]
Each of these need documentation for: markup, correct input types, patterns, validation setup

When complete, please edit the issue to strike through the item, and leave a link to the documentation for this.
- buttons with primary/secondary styles (ok/cancel)

http://master.origin.formcore.fgtest.com/views/text-inputs.html:
- ~~textarea~~
- ~~text input~~
- ~~number~~
- ~~password~~
- ~~password confirm (must match value in password)~~
- ~~email~~
- ~~URL~~
- ~~tel~~
- ~~search input~~
- ~~date~~
- ~~datetime~~
- ~~month~~
- ~~file input~~
- ~~color (or rec not to use?)~~
- ~~range (or rec not to use?)~~

http://master.origin.formcore.fgtest.com/views/selects.html:
- ~~native select~~
- ~~select with custom feedback button~~

http://master.origin.formcore.fgtest.com/views/checks-radios.html
- ~~checkbox~~
- ~~radiobutton set~~

http://master.origin.formcore.fgtest.com:
- ~~CVV code~~
- ~~credit card (just numeric w/length)~~
- ~~cc expiration MM YYYY~~
- ~~zip code (5 digit vs. extended) vs. postal code~~
-  ~~birthday: date vs. mm/yyyy inputs or dropdowns~~
- ~~name first, last vs. single first last input~~
- ~~currency amount (with options to change currency indicator on field - $ to left, euro right)~~

**Comment by zachleat** [comment]
Is this complete @maggiewachs?
