### ISSUE TITLE
Firefox isn't getting maxlength right

### ISSUE THREAD

**Issue by toddparker** [filamentgroup/formcore#42]
On FF, setting `maxlength="20"` ends up stopping input at 18 characters

![image](https://cloud.githubusercontent.com/assets/359929/15834940/cc92006e-2bfb-11e6-94a5-3fb8b75bb6ff.png)

![image](https://cloud.githubusercontent.com/assets/359929/15834949/db8b06b0-2bfb-11e6-9b41-01a2f98923d6.png)

**Comment by toddparker** [comment]
This will close vv issue #1149

**Comment by zachleat** [comment]
@toddparker if you cc from the private project issue, it should create a private link from here.

**Comment by johnbender** [comment]
That issue was closed. Closing here too.
