### ISSUE TITLE
Use `data-formcore-maxlength` instead of overloading `maxlength` for numeric inputs

### ISSUE THREAD

**Issue by johnbender** [filamentgroup/formcore#63]
The spec doesn't support `maxlength` on numeric inputs and `max` isn't always suitable but we shouldn't overload `maxlength` and using a data attribute makes it clear in the markup that formcore is performing the task of length restrictions.

**Comment by johnbender** [comment]
@toddparker @zachleat 

I'm curious about use-cases where `max` doesn't work.

**Comment by toddparker** [comment]
I believe `min` and `max` are intended for the min/max _value_ which is different than _string length_. You could enforce a maxlength of 5 characters of sorts by setting `max="99999"` but that seems a bit of a stretch for something like zip code. I see your point though...worth a dig through the spec.

**Comment by johnbender** [comment]
@toddparker 

Yah I'm just curious if there are cases where the string length can't be controlled by the maximum value. `max` is HTML5 so maybe the support is insufficient?
